import NextHead from "next/head";
import React from "react";

export default function Head() {
  return (
    <NextHead>
      <title>Twitter Clone</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta httpEquiv="refresh" content="1900" />
    </NextHead>
  );
}
